### ISSUE TITLE
Morning session: Peer-to-peer code review

### ISSUE THREAD

**Issue by Jord4N-AC** [NicolasAndrehh/JavaScript-Group-Capstone#32]
@johnie261, @NicolasAndrehh, you have done a fantastic job so far, but we have spotted some important suggestions that could make it even better.

**Highlights**

- Nice look and feel
- Features working as expected
- You meet best practices for HTML, CSS & JavaScript
- You meet DRY, YAGNI, KISS principles

**Suggestions**

- Kindly implement focus event to the likes buttons, in order to change the color of the button once the user clicks on it
- Kindly use an arrow function [in this part](https://github.com/NicolasAndrehh/JavaScript-Group-Capstone/blob/a9167fffc78d73475c1e4232bbe8c6de5237be52/src/modules/pageRenderer.js#L18-L25)

**_You are doing well, keep up the hard work!_** 💯

**Comment by NicolasAndrehh** [comment]
Hey @Jord4N-AC, I hope you doing well! 😄

Thank you so much for the feedback, all the suggestions were implemented on the last PR so you can check for it on the development branch!
